### ISSUE TITLE
[Bug?] Broken encoding in console input editbox

### ISSUE THREAD

**Issue by BlackDoomer** [klenin/cats-main#115]
When I write something in Russian into console editbox and then press Ctrl+Enter (habitually by chat in vk), console page reupdates but with mess in editbox instead of entered text.
Written text isn't sent to console in this case.
Firefox 39.0.

Example:
before: тесттесттест
after: ÑÐµÑÑÑÐµÑÑÑÐµÑÑ

**Comment by klenin** [comment]
Should be fixed since 16c654abc9e04b888b7563dcdff7dad1071a71ea
