### ISSUE TITLE
Добавить компилятор ABC.NET PASCAL 3

### ISSUE THREAD

**Issue by jazator** [klenin/cats-main#130]
Добавить компилятор ABC.NET PASCAL 3.2 
http://pascalabc.net/

Это позволит привлечь больше участников из школьников. Т.к. данный Паскаль широко распространён во многих школах по России.

**Comment by jazator** [comment]
Зарегистрировался у вас, получается, что у вас разночтения на странице Компиляторы и при выборе Среды разработки при отправке задач. Список значительно богаче. Даже есть ABC.NET, но к сожалению устаревшей версии. Как-то можно её обновить до 3.2 версии?

**Comment by klenin** [comment]
@jazator Александр Кленин:
Списки должны точно совпадать. Предлагаю пролистать страницы. Обновить Рascal можно

**Comment by jazator** [comment]
Приношу извинения, не увидел переключателей страниц... 
Просьба тогда обновить до версии, 3.2. Она того стоит. Небольшое сравнение с новой версией https://goo.gl/gfY6hG 
Спасибо!

**Comment by klenin** [comment]
Обновил

**Comment by jazator** [comment]
Благодарю!
