### ISSUE TITLE
Allow bigger time limits for dynamic languages

### ISSUE THREAD

**Issue by FooBarrior** [klenin/cats-main#154]
I think it's quite allowable for some contests to increase time limits by some multiple for dynamic language.

My proposal is to add a parameter for such multiplier into contest configuration

**Comment by klenin** [comment]
I have no problem with contest-specific limit changes for both time and memory.
Patches are welcome for that (you need to add corresponding fields to `contest_problems`, etc).
There is even a plan for per-request override (by @JIukaviy).

However, I disagree about language-specific limits -- this is IMO too fragile.

**Comment by klenin** [comment]
Time limit can now be assigned per-contest, see #163
