### ISSUE TITLE
"Прилинковать задачу" : не работает

### ISSUE THREAD

**Issue by grenkin** [klenin/cats-main#329]
Система предлагает задачи до русской буквы М. Остальные задачи не показываются и не ищутся через поиск.

**Comment by klenin** [comment]
Используй запрос формы title~=название

**Comment by grenkin** [comment]
В консоли аналогичная проблема - показывается ограниченное число попыток. Если выбрать задачу через фильтр, то можно будет посмотреть попытки по ней и в более ранние даты. А если просто ввести в поиск название задачи, то тоже не все попытки отобразятся.
