### ISSUE TITLE
[UX] Run details page

### ISSUE THREAD

**Issue by getjump** [klenin/cats-main#33]
User expierence improvance for run details page

* ~~Definitely, "Compare" button shouldn't display for users, who don't have that ability~~
* Some information from other users runs display even if not jury, we should check that case completely
* By default, will be better if that page(from console for ex.) will open in new window, like this ![ex](http://i.imgur.com/mGRxKNo.png)
* It will be nice, if we have option to watch testcase for failed test if some contest flag nor contest is not official(for ex.)
* Would be nice in case of runtime error or security violation display number of string that caused error, i think it is possible to do that

**Comment by klenin** [comment]
>By default, will be better if that page(from console for ex.) will open in new window, like this 
Extracted into #119.

>option to watch testcase for failed test
Done, see b557eb8a59f6acd7353c0e3f346793233faa179a

>runtime error or security violation display number of string that caused error,
Extracted to #120.
