### ISSUE TITLE
[UX] Teams in contest

### ISSUE THREAD

**Issue by getjump** [klenin/cats-main#36]
User expierence improvance for teams page
- It was really hard for me to locate pagination, intuitively it should be in down-right corner(why not just put a copy of it?) ![ex](http://i.imgur.com/EQRMleI.png)

**Comment by FooBarrior** [comment]
imho it's handy to have pages in middle of page, as it's not so far for mouse to move, in comparison with the bottom-right corner
you also able to use "показать" button to the right
